### ISSUE TITLE
Bootnodes issue ?

### ISSUE THREAD

**Issue by Vinche59** [AlveyCoin/validator#4]
Hello,

Is there a problem with the 2 bootnodes listed in genesis.json ?

```
"bootnodes": [
        "/ip4/95.179.246.28/tcp/1478/p2p/16Uiu2HAkxcdj1KNakRqyXm49PQmsFLqFGh41MpXbqJNoSU2ssPWP",
        "/ip4/185.92.221.129/tcp/1478/p2p/16Uiu2HAkzTsrGRdpzoPD8NRScgRyXmfrprMf1xC4NN7wHxT82EK1"
    ]
```
My node does not seem to be able to connect to those.

**Comment by sippikdf** [comment]
I think so , I can't run the node.

**Comment by Vinche59** [comment]
The bootnodes has been rebooted some days ago. I forgot to close this ticket.
